create table if not exists users
(
    id    bigint generated by default as identity primary key,
    name  varchar(250) not null,
    email varchar(254) not null,
    constraint uq_user_email unique (email)
);

create table if not exists categories
(
    id    bigint generated by default as identity primary key,
    name  varchar(50) not null,
    constraint uq_category_name unique (name)
);