create table if not exists endpoint_hits
(
    id    bigint generated by default as identity primary key,
    app  varchar(100),
    uri  varchar(100),
    ip  varchar(100),
    timestamp timestamp without time zone
);
--
-- create table if not exists items
-- (
--     id          bigint generated by default as identity primary key,
--     name        varchar(50)  not null,
--     description varchar(200) not null,
--     available   boolean      not null,
--     request_id  bigint,
--     user_id     bigint       not null ,
--     constraint "items_users_id_fk"
--         foreign key (user_id) references users ON DELETE CASCADE
-- );
--
-- create table if not exists bookings
-- (
--     id         bigint generated by default as identity primary key,
--     start_date timestamp without time zone not null,
--     end_date   timestamp without time zone not null,
--     item_id    bigint                      not null
--         constraint bookings_items_id_fk
--             references items ON DELETE CASCADE,
--     booker_id  bigint                      not null
--         constraint bookings_users_id_fk
--             references users ON DELETE CASCADE,
--     status     varchar(15)                 not null
-- );
--
-- create table if not exists comments
-- (
--     id        bigint generated by default as identity primary key,
--     text      varchar(600)                not null,
--     item_id   bigint                      not null
--         constraint comments_items_id_fk
--             references items ON DELETE CASCADE,
--     author_id bigint                      not null
--         constraint comments_users_id_fk
--             references users ON DELETE CASCADE,
--     created   timestamp without time zone not null
-- );
--
-- create table if not exists requests
-- (
--     id           bigint generated by default as identity primary key,
--     description  varchar(200) not null,
--     user_id      bigint       not null
--     constraint "users_items_id_fk"
--         references users ON DELETE CASCADE,
--     created   timestamp without time zone not null
-- );

