create table if not exists users
(
    id    bigint generated by default as identity primary key,
    name  varchar(100) not null ,
    email varchar(50) not null,
    constraint uq_user_email unique (email)
);