version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    image: stats_server_image
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm_stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
